POST http://localhost:3000/alunos
Content-Type: application/json

{
    "nome": "Roberto",
    "turma": "2B",
    "notas": [
        {"disciplina": "matemática", "nota": 8},
        {"disciplina": "história", "nota": 9}
    ] 
}

###

GET http://localhost:3000/alunos
Content-Type: application/json

###

PUT http://localhost:3000/alunos/a61d6c75-9177-4687-bc3f-200f0bbf5423
Content-Type: application/json

{
    "nome": "Lucas",
    "turma": "2A",
    "notas": [
        {"disciplina": "matemática", "nota": 8},
        {"disciplina": "história", "nota": 9},
        {"disciplina": "português", "nota": 5}
    ] 
}

###

DELETE http://localhost:3000/alunos/4b789bb2-b227-4964-84bd-e450582ff223