POST http://localhost:3000/aluno
Content-Type: application/json

{
    "nome": "Roberto",
    "turma": "2B",
    "notas": [
        {"disciplina": "matemática", "nota": 8},
        {"disciplina": "história", "nota": 9}
    ] 
}

###

GET http://localhost:3000/alunos
Content-Type: application/json

###

PUT http://localhost:3000/aluno/a28c3052-5b1d-4eec-b6c9-12202cc1ba18
Content-Type: application/json

{
    "nome": "Matheus",
    "turma": "2B",
    "notas": [
        {"disciplina": "matemática", "nota": 8},
        {"disciplina": "história", "nota": 9},
        {"disciplina": "biologia", "nota": 6}
    ] 
}

###

DELETE http://localhost:3000/aluno/4b789bb2-b227-4964-84bd-e450582ff223